version: '3'
services:

  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
